
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.7 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "vectorblox_mxp.h"

/*
* The configuration table for devices
*/

VectorBlox_MXP_Config VectorBlox_MXP_ConfigTable[] =
{
	{
		XPAR_VECTORBLOX_MXP_ARM_0_DEVICE_ID,
		XPAR_VECTORBLOX_MXP_ARM_0_S_AXI_BASEADDR,
		XPAR_VECTORBLOX_MXP_ARM_0_S_AXI_HIGHADDR,
		XPAR_VECTORBLOX_MXP_ARM_0_VECTOR_LANES,
		XPAR_VECTORBLOX_MXP_ARM_0_SCRATCHPAD_KB,
		XPAR_VECTORBLOX_MXP_ARM_0_M_AXI_DATA_WIDTH,
		XPAR_VECTORBLOX_MXP_ARM_0_MULFXP_WORD_FRACTION_BITS,
		XPAR_VECTORBLOX_MXP_ARM_0_MULFXP_HALF_FRACTION_BITS,
		XPAR_VECTORBLOX_MXP_ARM_0_MULFXP_BYTE_FRACTION_BITS,
		XPAR_VECTORBLOX_MXP_ARM_0_CLOCK_FREQ_HZ,
		XPAR_VECTORBLOX_MXP_ARM_0_S_AXI_INSTR_BASEADDR,
		XPAR_VECTORBLOX_MXP_ARM_0_VCI_LANES
	}
};


