include ../../common/xil_app_vars.mk
include sources.mk

ALT_LIBRARY_ROOT_DIR := ../../lib/vbxware
include ../../lib/vbxware/public.mk
ALT_LIBRARY_ROOT_DIR := ../../lib/vbxtest
include ../../lib/vbxtest/public.mk
ALT_LIBRARY_ROOT_DIR := ../../lib/scalar
include ../../lib/scalar/public.mk
ALT_LIBRARY_ROOT_DIR := ../../lib/libfixmath
include ../../lib/libfixmath/public.mk

include ../../common/xil_app.mk
